ADD_SCENE(desktop_settings, start, Start)
ADD_SCENE(desktop_settings, keybinds_type, KeybindsType)
ADD_SCENE(desktop_settings, keybinds_key, KeybindsKey)
ADD_SCENE(desktop_settings, keybinds_choose, KeybindsChoose)
ADD_SCENE(desktop_settings, pin_menu, PinMenu)

ADD_SCENE(desktop_settings, pin_auth, PinAuth)
ADD_SCENE(desktop_settings, pin_error, PinError)
ADD_SCENE(desktop_settings, pin_disable, PinDisable)
ADD_SCENE(desktop_settings, pin_setup, PinSetup)
ADD_SCENE(desktop_settings, pin_setup_howto, PinSetupHowto)
ADD_SCENE(desktop_settings, pin_setup_howto2, PinSetupHowto2)
ADD_SCENE(desktop_settings, pin_setup_done, PinSetupDone)
