ADD_SCENE(bad_kb, file_select, FileSelect)
ADD_SCENE(bad_kb, work, Work)
ADD_SCENE(bad_kb, error, Error)
ADD_SCENE(bad_kb, config_bt, ConfigBt)
ADD_SCENE(bad_kb, config_usb, ConfigUsb)
ADD_SCENE(bad_kb, config_layout, ConfigLayout)
ADD_SCENE(bad_kb, config_name, ConfigName)
ADD_SCENE(bad_kb, config_mac, ConfigMac)
