ADD_SCENE(bad_usb, file_select, FileSelect)
ADD_SCENE(bad_usb, work, Work)
ADD_SCENE(bad_usb, error, Error)
ADD_SCENE(bad_usb, config_bt, ConfigBt)
ADD_SCENE(bad_usb, config_usb, ConfigUsb)
ADD_SCENE(bad_usb, config_layout, ConfigLayout)
ADD_SCENE(bad_usb, config_name, ConfigName)
ADD_SCENE(bad_usb, config_mac, ConfigMac)
